### ISSUE TITLE
when update to julia 1.0

### ISSUE THREAD

**Issue by aiyou9** [PacktPublishing/Hands-On-Computer-Vision-with-Julia#2]

**Comment by dmitrijsc** [comment]
I was planning to do it end of the year. Will create a separate branch for 1.0.

**Comment by githubce** [comment]
Author has provided the solution. Reopen if you want to continue discussion.

**Comment by 00krishna** [comment]
Say, was the code ever updated for Julia 1.0? The README still references Julia 0.6.3 is required, but the issue for updating to Julia 1.0 was closed. So it was not clear what the current status is. Thanks.
