### ISSUE TITLE
Newspaper sample image missing from directory

### ISSUE THREAD

**Issue by tjburch** [PacktPublishing/Hands-On-Computer-Vision-with-Julia#4]
Page 133 has an example using `sample-images/newspaper-37782_640.png`, which hasn't been included in this repository.

**Comment by dmitrijsc** [comment]
Hello @tjburch ! Thanks for you feedback!

I have used the image from pixabay. You can get it from https://pixabay.com/vectors/newspaper-paper-print-press-news-37782/

Will update the repo accordingly.
